[project]
name = "taxsee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-text-splitters>=0.3.5",
    "openai>=1.59.7",
    "timm>=1.0.13",
]
